apiVersion: apps/v1
kind: Deployment
metadata:
  name: app-three
  labels:
    app: app-three
spec:
  replicas: 1
  selector:
    matchLabels:
      app: app-three
  template:
    metadata:
      labels:
        app: app-three
    spec:
      containers:
      - name: app-three
        image: python:3.11-slim
        ports:
        - containerPort: 8000
        command: ["python", "-m", "http.server", "8000"]
        workingDir: /
